// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { create } from "./create.js";
import { focus } from "./focus.js";
import { KeyEvent } from "../types.js";
import { MaybeReactive } from "@monstermann/signals";
import { Memo } from "@monstermann/signals";
import { MouseEvent } from "../types.js";
import { PasteEvent } from "../types.js";
import { ReadonlyEmitter } from "@monstermann/signals";
import { ReadonlySignal } from "@monstermann/signals";

interface Element {
    bottom: Memo<number>
    col: Memo<number>
    height: Memo<number>
    isFocused: ReadonlySignal<boolean>
    isMounted: ReadonlySignal<boolean>
    left: Memo<number>
    maxHeight: Memo<number>
    maxWidth: Memo<number>
    onBlur: ReadonlyEmitter<void>
    onFocus: ReadonlyEmitter<void>
    onKeypress: ReadonlyEmitter<KeyEvent>
    onMount: ReadonlyEmitter<void>
    onMouse: ReadonlyEmitter<MouseEvent>
    onPaste: ReadonlyEmitter<PasteEvent>
    onRender: ReadonlyEmitter<void>
    onUnmount: ReadonlyEmitter<void>
    right: Memo<number>
    row: Memo<number>
    top: Memo<number>
    width: Memo<number>
    mount: () => void
}

interface ElementOptions {
    col?: MaybeReactive<number>
    height?: MaybeReactive<number>
    row?: MaybeReactive<number>
    width?: MaybeReactive<number>
    onBlur?: () => void
    onFocus?: () => void
    onKeypress?: (event: KeyEvent) => void
    onMount?: () => void
    onMouse?: (event: MouseEvent) => void
    onPaste?: (event: PasteEvent) => void
    onRender?: () => void
    onUnmount?: () => void
}

declare namespace Element {
    export {
        create,
        focus,
    }
}

export {
    Element,
    ElementOptions,
}
