// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { fillAround } from "./fillAround.js";
import { fillLeft } from "./fillLeft.js";
import { fillRight } from "./fillRight.js";
import { isAscii } from "./isAscii.js";
import { splitAt } from "./splitAt.js";
import { truncateLeft } from "./truncateLeft.js";
import { truncateRight } from "./truncateRight.js";
import { width } from "./width.js";

export const Str = {
    fillAround,
    fillLeft,
    fillRight,
    isAscii,
    splitAt,
    truncateLeft,
    truncateRight,
    width,
}
