// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { cols } from "./cols.js";
import { compact } from "./compact.js";
import { fillAround } from "./fillAround.js";
import { fillLeft } from "./fillLeft.js";
import { fillRight } from "./fillRight.js";
import { inheritStyle } from "./inheritStyle.js";
import { mergeStyle } from "./mergeStyle.js";
import { truncateLeft } from "./truncateLeft.js";
import { truncateRight } from "./truncateRight.js";
import { width } from "./width.js";

declare namespace Line {
    export {
        cols,
        compact,
        fillAround,
        fillLeft,
        fillRight,
        inheritStyle,
        mergeStyle,
        truncateLeft,
        truncateRight,
        width,
    }
}

export {
    Line,
}
