// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { arrow } from "./borders.js";
import { bold } from "./borders.js";
import { classic } from "./borders.js";
import { create } from "./create.js";
import { double } from "./borders.js";
import { round } from "./borders.js";
import { single } from "./borders.js";

export const Box = {
    arrow,
    bold,
    classic,
    create,
    double,
    round,
    single,
}
