// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { arrow } from "./borders.js";
import { bold } from "./borders.js";
import { classic } from "./borders.js";
import { create } from "./create.js";
import { double } from "./borders.js";
import { Element } from "../Element/index.js";
import { ElementOptions } from "../Element/index.js";
import { MaybeReactive } from "@monstermann/signals";
import { Memo } from "@monstermann/signals";
import { round } from "./borders.js";
import { single } from "./borders.js";
import { Style } from "../Style/index.js";
import { Text } from "../Text/index.js";

interface Box extends Element {
    innerCol: Memo<number>
    innerHeight: Memo<number>
    innerRow: Memo<number>
    innerWidth: Memo<number>
    lines: Memo<Text[][]>
    render: () => void
}

interface BoxOptions extends ElementOptions {
    border?: MaybeReactive<BorderShape>
    style?: MaybeReactive<Style>
    padding?: {
        b?: MaybeReactive<number>
        l?: MaybeReactive<number>
        r?: MaybeReactive<number>
        t?: MaybeReactive<number>
    }
    titles?: {
        b?: MaybeReactive<Text>
        bl?: MaybeReactive<Text>
        br?: MaybeReactive<Text>
        padding?: MaybeReactive<number>
        t?: MaybeReactive<Text>
        tl?: MaybeReactive<Text>
        tr?: MaybeReactive<Text>
    }
}

interface BorderShape {
    b: string
    bl: string
    br: string
    l: string
    r: string
    t: string
    tl: string
    tr: string
}

declare namespace Box {
    export {
        arrow,
        bold,
        classic,
        create,
        double,
        round,
        single,
    }
}

export {
    Box,
    BorderShape,
    BoxOptions,
}
