// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { create } from "./create.js";
import { drawLine } from "./drawLine.js";
import { drawLines } from "./drawLines.js";
import { drawText } from "./drawText.js";
import { patch } from "./patch.js";
import { Style } from "../Style/index.js";

interface Cell {
    readonly style: Style
    readonly value: string
    readonly width: number
}

type FrameBuffer = Cell[][]

declare namespace FrameBuffer {
    export {
        create,
        drawLine,
        drawLines,
        drawText,
        patch,
    }
}

export {
    FrameBuffer,
    Cell,
}
