// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { create } from "./create.js";
import { drawLine } from "./drawLine.js";
import { drawLines } from "./drawLines.js";
import { drawText } from "./drawText.js";
import { patch } from "./patch.js";

export const FrameBuffer = {
    create,
    drawLine,
    drawLines,
    drawText,
    patch,
}
