// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { Box } from "../Box/index.js";
import { create } from "./create.js";
import { Data } from "../Data/index.js";
import { ElementOptions } from "../Element/index.js";
import { List } from "../List/index.js";
import { MaybeReactive } from "@monstermann/signals";
import { Token } from "../Data/internals/Tokenizer.js";

interface Logs {
    box: Box
    list: List<LogData>
    render: () => void
}

interface LogData {
    data: Data
    path: string
    tokens: Token[]
}

interface LogsOptions extends ElementOptions {
    max?: MaybeReactive<number>
}

declare namespace Logs {
    export {
        create,
    }
}

export {
    Logs,
    LogData,
    LogsOptions,
}
