// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { matches } from "./matches.js";
import { onShortcut } from "./onShortcut.js";
import { onShortcuts } from "./onShortcuts.js";
import { text } from "./text.js";

declare namespace Key {
    export {
        matches,
        onShortcut,
        onShortcuts,
        text,
    }
}

export {
    Key,
}
