// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { CharType } from "./type.js";
import { isAscii } from "./isAscii.js";
import { type } from "./type.js";
import { width } from "./width.js";

declare namespace Char {
    export {
        isAscii,
        type,
        width,
    }
}

export {
    Char,
    CharType,
}
