// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { isAscii } from "./isAscii.js";
import { type } from "./type.js";
import { width } from "./width.js";

export const Char = {
    isAscii,
    type,
    width,
}
