// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { aesthetic } from "./spinners.js";
import { arc } from "./spinners.js";
import { arrow } from "./spinners.js";
import { arrow2 } from "./spinners.js";
import { arrow3 } from "./spinners.js";
import { balloon } from "./spinners.js";
import { balloon2 } from "./spinners.js";
import { betaWave } from "./spinners.js";
import { binary } from "./spinners.js";
import { bluePulse } from "./spinners.js";
import { bounce } from "./spinners.js";
import { bouncingBall } from "./spinners.js";
import { bouncingBar } from "./spinners.js";
import { boxBounce } from "./spinners.js";
import { boxBounce2 } from "./spinners.js";
import { christmas } from "./spinners.js";
import { circle } from "./spinners.js";
import { circleHalves } from "./spinners.js";
import { circleQuarters } from "./spinners.js";
import { clock } from "./spinners.js";
import { create } from "./create.js";
import { dots } from "./spinners.js";
import { dots10 } from "./spinners.js";
import { dots11 } from "./spinners.js";
import { dots12 } from "./spinners.js";
import { dots13 } from "./spinners.js";
import { dots14 } from "./spinners.js";
import { dots2 } from "./spinners.js";
import { dots3 } from "./spinners.js";
import { dots4 } from "./spinners.js";
import { dots5 } from "./spinners.js";
import { dots6 } from "./spinners.js";
import { dots7 } from "./spinners.js";
import { dots8 } from "./spinners.js";
import { dots8Bit } from "./spinners.js";
import { dots9 } from "./spinners.js";
import { dotsCircle } from "./spinners.js";
import { dqpb } from "./spinners.js";
import { dwarfFortress } from "./spinners.js";
import { earth } from "./spinners.js";
import { fingerDance } from "./spinners.js";
import { fistBump } from "./spinners.js";
import { flip } from "./spinners.js";
import { grenade } from "./spinners.js";
import { growHorizontal } from "./spinners.js";
import { growVertical } from "./spinners.js";
import { hamburger } from "./spinners.js";
import { hearts } from "./spinners.js";
import { layer } from "./spinners.js";
import { line } from "./spinners.js";
import { line2 } from "./spinners.js";
import { material } from "./spinners.js";
import { Memo } from "@monstermann/signals";
import { mindblown } from "./spinners.js";
import { monkey } from "./spinners.js";
import { moon } from "./spinners.js";
import { noise } from "./spinners.js";
import { orangeBluePulse } from "./spinners.js";
import { orangePulse } from "./spinners.js";
import { pipe } from "./spinners.js";
import { point } from "./spinners.js";
import { pong } from "./spinners.js";
import { rollingLine } from "./spinners.js";
import { runner } from "./spinners.js";
import { sand } from "./spinners.js";
import { shark } from "./spinners.js";
import { Signal } from "@monstermann/signals";
import { simpleDots } from "./spinners.js";
import { simpleDotsScrolling } from "./spinners.js";
import { smiley } from "./spinners.js";
import { soccerHeader } from "./spinners.js";
import { speaker } from "./spinners.js";
import { squareCorners } from "./spinners.js";
import { squish } from "./spinners.js";
import { star } from "./spinners.js";
import { star2 } from "./spinners.js";
import { Style } from "../Style/index.js";
import { Text } from "../Text/index.js";
import { timeTravel } from "./spinners.js";
import { toggle } from "./spinners.js";
import { toggle10 } from "./spinners.js";
import { toggle11 } from "./spinners.js";
import { toggle12 } from "./spinners.js";
import { toggle13 } from "./spinners.js";
import { toggle2 } from "./spinners.js";
import { toggle3 } from "./spinners.js";
import { toggle4 } from "./spinners.js";
import { toggle5 } from "./spinners.js";
import { toggle6 } from "./spinners.js";
import { toggle7 } from "./spinners.js";
import { toggle8 } from "./spinners.js";
import { toggle9 } from "./spinners.js";
import { triangle } from "./spinners.js";
import { weather } from "./spinners.js";

interface SpinnerOptions {
    frames: readonly string[]
    interval: number
    style?: Style
}

interface Spinner {
    isRunning: Signal<boolean>
    text: Memo<Text>
    start: () => void
    stop: () => void
}

declare namespace Spinner {
    export {
        aesthetic,
        arc,
        arrow,
        arrow2,
        arrow3,
        balloon,
        balloon2,
        betaWave,
        binary,
        bluePulse,
        bounce,
        bouncingBall,
        bouncingBar,
        boxBounce,
        boxBounce2,
        christmas,
        circle,
        circleHalves,
        circleQuarters,
        clock,
        create,
        dots,
        dots10,
        dots11,
        dots12,
        dots13,
        dots14,
        dots2,
        dots3,
        dots4,
        dots5,
        dots6,
        dots7,
        dots8,
        dots8Bit,
        dots9,
        dotsCircle,
        dqpb,
        dwarfFortress,
        earth,
        fingerDance,
        fistBump,
        flip,
        grenade,
        growHorizontal,
        growVertical,
        hamburger,
        hearts,
        layer,
        line,
        line2,
        material,
        mindblown,
        monkey,
        moon,
        noise,
        orangeBluePulse,
        orangePulse,
        pipe,
        point,
        pong,
        rollingLine,
        runner,
        sand,
        shark,
        simpleDots,
        simpleDotsScrolling,
        smiley,
        soccerHeader,
        speaker,
        squareCorners,
        squish,
        star,
        star2,
        timeTravel,
        toggle,
        toggle10,
        toggle11,
        toggle12,
        toggle13,
        toggle2,
        toggle3,
        toggle4,
        toggle5,
        toggle6,
        toggle7,
        toggle8,
        toggle9,
        triangle,
        weather,
    }
}

export {
    Spinner,
    SpinnerOptions,
}
