// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { alternateScreen } from "./alternateScreen.js";
import { col } from "./col.js";
import { colorScheme } from "./colorScheme.js";
import { cursor } from "./cursor.js";
import { dimension } from "./dimension.js";
import { drawLine } from "./drawLine.js";
import { drawLines } from "./drawLines.js";
import { drawText } from "./drawText.js";
import { enterAlternateScreen } from "./enterAlternateScreen.js";
import { exit } from "./exit.js";
import { exitAlternateScreen } from "./exitAlternateScreen.js";
import { hasCursor } from "./hasCursor.js";
import { height } from "./height.js";
import { hideCursor } from "./hideCursor.js";
import { isFocused } from "./isFocused.js";
import { isWithin } from "./isWithin.js";
import { onBlur } from "./onBlur.js";
import { onCtrlC } from "./onCtrlC.js";
import { onExit } from "./onExit.js";
import { onFocus } from "./onFocus.js";
import { onKey } from "./onKey.js";
import { onMouse } from "./onMouse.js";
import { onMove } from "./onMove.js";
import { onPaste } from "./onPaste.js";
import { onResize } from "./onResize.js";
import { onShortcut } from "./onShortcut.js";
import { onShortcuts } from "./onShortcuts.js";
import { render } from "./render.js";
import { row } from "./row.js";
import { setCursor } from "./setCursor.js";
import { showCursor } from "./showCursor.js";
import { startCapturingInput } from "./startCapturingInput.js";
import { stopCapturingInput } from "./startCapturingInput.js";
import { width } from "./width.js";
import { write } from "./write.js";

export const Term = {
    alternateScreen,
    col,
    colorScheme,
    cursor,
    dimension,
    drawLine,
    drawLines,
    drawText,
    enterAlternateScreen,
    exit,
    exitAlternateScreen,
    hasCursor,
    height,
    hideCursor,
    isFocused,
    isWithin,
    onBlur,
    onCtrlC,
    onExit,
    onFocus,
    onKey,
    onMouse,
    onMove,
    onPaste,
    onResize,
    onShortcut,
    onShortcuts,
    render,
    row,
    setCursor,
    showCursor,
    startCapturingInput,
    stopCapturingInput,
    width,
    write,
}
