// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { create } from "./create.js";
import { inheritStyle } from "./inheritStyle.js";
import { mergeStyle } from "./mergeStyle.js";
import { Style } from "../Style/index.js";
import { symbol } from "./internals.js";
import { width } from "./width.js";

interface Text {
    readonly style: Style
    readonly [symbol]: true
    readonly value: string
}

declare namespace Text {
    export {
        create,
        inheritStyle,
        mergeStyle,
        width,
    }
}

export {
    Text,
}
