// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { create } from "./create.js";
import { inheritStyle } from "./inheritStyle.js";
import { mergeStyle } from "./mergeStyle.js";
import { width } from "./width.js";

export const Text = {
    create,
    inheritStyle,
    mergeStyle,
    width,
}
