import { defineConfig } from "vitepress"
import { groupIconMdPlugin, groupIconVitePlugin } from "vitepress-plugin-group-icons"

export default defineConfig({
    base: "/signals-tui/",
    description: "Declarative TUI framework using signals.",
    title: "signals-tui",
    markdown: {
        theme: {
            dark: "catppuccin-macchiato",
            light: "github-light-default",
        },
        config(md) {
            md.use(groupIconMdPlugin)
        },
    },
    themeConfig: {
        aside: false,
        outline: "deep",
        docFooter: {
            next: false,
            prev: false,
        },
        search: {
            provider: "local",
        },
        sidebar: [
            { text: "Core", items: [
                { base: "/Term/", collapsed: true, text: "Term", items: [
                    { link: "alternateScreen", text: "alternateScreen" },
                    { link: "colorScheme", text: "colorScheme" },
                    { link: "col", text: "col" },
                    { link: "cursor", text: "cursor" },
                    { link: "dimension", text: "dimension" },
                    { link: "drawLines", text: "drawLines" },
                    { link: "drawLine", text: "drawLine" },
                    { link: "drawText", text: "drawText" },
                    { link: "enterAlternateScreen", text: "enterAlternateScreen" },
                    { link: "exitAlternateScreen", text: "exitAlternateScreen" },
                    { link: "exit", text: "exit" },
                    { link: "hasCursor", text: "hasCursor" },
                    { link: "height", text: "height" },
                    { link: "hideCursor", text: "hideCursor" },
                    { link: "isFocused", text: "isFocused" },
                    { link: "isWithin", text: "isWithin" },
                    { link: "onBlur", text: "onBlur" },
                    { link: "onCtrlC", text: "onCtrlC" },
                    { link: "onExit", text: "onExit" },
                    { link: "onFocus", text: "onFocus" },
                    { link: "onKey", text: "onKey" },
                    { link: "onMouse", text: "onMouse" },
                    { link: "onMove", text: "onMove" },
                    { link: "onPaste", text: "onPaste" },
                    { link: "onResize", text: "onResize" },
                    { link: "onShortcuts", text: "onShortcuts" },
                    { link: "onShortcut", text: "onShortcut" },
                    { link: "render", text: "render" },
                    { link: "row", text: "row" },
                    { link: "setCursor", text: "setCursor" },
                    { link: "showCursor", text: "showCursor" },
                    { link: "startCapturingInput", text: "startCapturingInput" },
                    { link: "stopCapturingInput", text: "stopCapturingInput" },
                    { link: "width", text: "width" },
                    { link: "write", text: "write" },
                ] },
                { base: "/Text/", collapsed: true, text: "Text", items: [
                    { link: "create", text: "create" },
                    { link: "inheritStyle", text: "inheritStyle" },
                    { link: "mergeStyle", text: "mergeStyle" },
                    { link: "width", text: "width" },
                ] },
                { base: "/Style/", collapsed: true, text: "Style", items: [
                    { link: "ansi", text: "ansi" },
                    { link: "create", text: "create" },
                    { link: "hash", text: "hash" },
                    { link: "inherit", text: "inherit" },
                    { link: "merge", text: "merge" },
                ] },
            ] },
            { text: "Elements", items: [
                { base: "/Box/", collapsed: true, text: "Box", items: [
                    { link: "create", text: "create" },
                    { link: "borders", text: "borders" },
                ] },
                { base: "/Data/", collapsed: true, text: "Data", items: [
                    { link: "collapse", text: "collapse" },
                    { link: "create", text: "create" },
                    { link: "expand", text: "expand" },
                    { link: "toggle", text: "toggle" },
                ] },
                { base: "/Input/", collapsed: true, text: "Input", items: [
                    { link: "blur", text: "blur" },
                    { link: "create", text: "create" },
                    { link: "focus", text: "focus" },
                    { link: "moveLeft", text: "moveLeft" },
                    { link: "moveRight", text: "moveRight" },
                    { link: "removeLeft", text: "removeLeft" },
                    { link: "removeRight", text: "removeRight" },
                    { link: "reset", text: "reset" },
                    { link: "set", text: "set" },
                    { link: "write", text: "write" },
                ] },
                { base: "/Logs/", collapsed: true, text: "Logs", items: [
                    { link: "create", text: "create" },
                ] },
                { base: "/List/", collapsed: true, text: "List", items: [
                    { link: "create", text: "create" },
                    { link: "focus", text: "focus" },
                    { link: "isAtBottom", text: "isAtBottom" },
                    { link: "isAtTop", text: "isAtTop" },
                    { link: "isSelectable", text: "isSelectable" },
                    { link: "nextSelectable", text: "nextSelectable" },
                    { link: "prevSelectable", text: "prevSelectable" },
                    { link: "scrollDownBy", text: "scrollDownBy" },
                    { link: "scrollDownHalfPage", text: "scrollDownHalfPage" },
                    { link: "scrollDownPage", text: "scrollDownPage" },
                    { link: "scrollToBottom", text: "scrollToBottom" },
                    { link: "scrollToTop", text: "scrollToTop" },
                    { link: "scrollUpBy", text: "scrollUpBy" },
                    { link: "scrollUpHalfPage", text: "scrollUpHalfPage" },
                    { link: "scrollUpPage", text: "scrollUpPage" },
                    { link: "select", text: "select" },
                    { link: "selectFirst", text: "selectFirst" },
                    { link: "selectLast", text: "selectLast" },
                    { link: "selectNext", text: "selectNext" },
                    { link: "selectPrev", text: "selectPrev" },
                    { link: "setScrollTop", text: "setScrollTop" },
                ] },
                { base: "/Spinner/", collapsed: true, text: "Spinner", items: [
                    { link: "create", text: "create" },
                    { link: "spinners", text: "spinners" },
                ] },
                { base: "/Table/", collapsed: true, text: "Table", items: [
                    { link: "create", text: "create" },
                ] },
            ] },
            { text: "Utils", items: [
                { base: "/Char/", collapsed: true, text: "Char", items: [
                    { link: "isAscii", text: "isAscii" },
                    { link: "type", text: "type" },
                    { link: "width", text: "width" },
                ] },
                { base: "/Chars/", collapsed: true, text: "Chars", items: [
                    { link: "create", text: "create" },
                    { link: "fillAround", text: "fillAround" },
                    { link: "fillLeft", text: "fillLeft" },
                    { link: "fillRight", text: "fillRight" },
                    { link: "nextWordOffset", text: "nextWordOffset" },
                    { link: "prevWordOffset", text: "prevWordOffset" },
                    { link: "truncateLeft", text: "truncateLeft" },
                    { link: "truncateRight", text: "truncateRight" },
                    { link: "width", text: "width" },
                ] },
                { base: "/Element/", collapsed: true, text: "Element", items: [
                    { link: "create", text: "create" },
                    { link: "focus", text: "focus" },
                ] },
                { base: "/FrameBuffer/", collapsed: true, text: "FrameBuffer", items: [
                    { link: "create", text: "create" },
                    { link: "drawLine", text: "drawLine" },
                    { link: "drawLines", text: "drawLines" },
                    { link: "drawText", text: "drawText" },
                    { link: "patch", text: "patch" },
                ] },
                { base: "/Line/", collapsed: true, text: "Line", items: [
                    { link: "cols", text: "cols" },
                    { link: "compact", text: "compact" },
                    { link: "fillAround", text: "fillAround" },
                    { link: "fillLeft", text: "fillLeft" },
                    { link: "fillRight", text: "fillRight" },
                    { link: "inheritStyle", text: "inheritStyle" },
                    { link: "mergeStyle", text: "mergeStyle" },
                    { link: "truncateLeft", text: "truncateLeft" },
                    { link: "truncateRight", text: "truncateRight" },
                    { link: "width", text: "width" },
                ] },
                { base: "/Str/", collapsed: true, text: "Str", items: [
                    { link: "fillAround", text: "fillAround" },
                    { link: "fillLeft", text: "fillLeft" },
                    { link: "fillRight", text: "fillRight" },
                    { link: "isAscii", text: "isAscii" },
                    { link: "splitAt", text: "splitAt" },
                    { link: "truncateLeft", text: "truncateLeft" },
                    { link: "truncateRight", text: "truncateRight" },
                    { link: "width", text: "width" },
                ] },
            ] },
        ],
        socialLinks: [
            { icon: "github", link: "https://github.com/MichaelOstermann/signals-tui" },
        ],
    },
    vite: {
        plugins: [
            groupIconVitePlugin(),
        ],
    },
})
