// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { create } from "./create.js";
import { Element } from "../Element/index.js";
import { ElementOptions } from "../Element/index.js";
import { MaybeReactive } from "@monstermann/signals";
import { Memo } from "@monstermann/signals";
import { Text } from "../Text/index.js";

interface Table<T extends object> extends Element {
    gap: Memo<number>
    lines: Memo<TableLine<T>[]>
    widths: Memo<number[]>
    render: () => void
}

interface TableLine<T extends object> {
    data: T
    line: Text[]
}

interface TableOptions<T extends object, U extends string> extends ElementOptions {
    columns: MaybeReactive<TableColumn<U>[]>
    data: MaybeReactive<T[]>
    gap?: MaybeReactive<Text[]>
    getBodyCell: (ctx: {
        col: NoInfer<U>
        colIdx: number
        data: NoInfer<T>
        rowIdx: number
    }) => string
    renderBodyCell?: (ctx: {
        col: NoInfer<U>
        colIdx: number
        content: string
        data: NoInfer<T>
        rawContent: string
        rowIdx: number
        width: number
    }) => Text[]
}

interface TableColumn<T extends string> {
    align?: "left" | "center" | "right"
    minWidth?: number
    name: T
    reserved?: boolean
}

declare namespace Table {
    export {
        create,
    }
}

export {
    Table,
    TableColumn,
    TableLine,
    TableOptions,
}
