// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { blur } from "./blur.js";
import { create } from "./create.js";
import { focus } from "./focus.js";
import { moveLeft } from "./moveLeft.js";
import { moveRight } from "./moveRight.js";
import { removeLeft } from "./removeLeft.js";
import { removeRight } from "./removeRight.js";
import { reset } from "./reset.js";
import { set } from "./set.js";
import { write } from "./write.js";

export const Input = {
    blur,
    create,
    focus,
    moveLeft,
    moveRight,
    removeLeft,
    removeRight,
    reset,
    set,
    write,
}
