// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { blur } from "./blur.js";
import { create } from "./create.js";
import { Element } from "../Element/index.js";
import { ElementOptions } from "../Element/index.js";
import { focus } from "./focus.js";
import { MaybeReactive } from "@monstermann/signals";
import { Memo } from "@monstermann/signals";
import { moveLeft } from "./moveLeft.js";
import { moveRight } from "./moveRight.js";
import { ReadonlySignal } from "@monstermann/signals";
import { removeLeft } from "./removeLeft.js";
import { removeRight } from "./removeRight.js";
import { reset } from "./reset.js";
import { set } from "./set.js";
import { Signal } from "@monstermann/signals";
import { Text } from "../Text/index.js";
import { write } from "./write.js";

interface InputOptions extends ElementOptions {
    placeholder?: MaybeReactive<Text>
    renderInput?: (input: Input) => Text[]
}

interface Input extends Element {
    chars: Signal<readonly string[]>
    index: Memo<number>
    line: Memo<Text[]>
    offset: Signal<number>
    prevCol: ReadonlySignal<number>
    prevRow: ReadonlySignal<number>
    scroll: Signal<number>
    value: Memo<string>
    render: () => void
}

declare namespace Input {
    export {
        blur,
        create,
        focus,
        moveLeft,
        moveRight,
        removeLeft,
        removeRight,
        reset,
        set,
        write,
    }
}

export {
    Input,
    InputOptions,
}
