// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { ansi } from "./ansi.js";
import { create } from "./create.js";
import { hash } from "./hash.js";
import { inherit } from "./inherit.js";
import { merge } from "./merge.js";

type Color =
    | "black"
    | "red"
    | "green"
    | "yellow"
    | "blue"
    | "magenta"
    | "cyan"
    | "white"
    | "brightBlack"
    | "brightRed"
    | "brightGreen"
    | "brightYellow"
    | "brightBlue"
    | "brightMagenta"
    | "brightCyan"
    | "brightWhite"

interface Style {
    readonly bg?: Color
    readonly bold?: boolean
    readonly dim?: boolean
    readonly fg?: Color
    readonly hidden?: boolean
    readonly inverse?: boolean
    readonly italic?: boolean
    readonly overline?: boolean
    readonly strikethrough?: boolean
    readonly underline?: boolean
}

declare namespace Style {
    export {
        ansi,
        create,
        hash,
        inherit,
        merge,
    }
}

export {
    Style,
    Color,
}
