// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { ansi } from "./ansi.js";
import { create } from "./create.js";
import { hash } from "./hash.js";
import { inherit } from "./inherit.js";
import { merge } from "./merge.js";

export const Style = {
    ansi,
    create,
    hash,
    inherit,
    merge,
}
