// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { fillAround } from "./fillAround.js";
import { fillLeft } from "./fillLeft.js";
import { fillRight } from "./fillRight.js";
import { nextWordOffset } from "./nextWordOffset.js";
import { prevWordOffset } from "./prevWordOffset.js";
import { truncateLeft } from "./truncateLeft.js";
import { truncateRight } from "./truncateRight.js";
import { width } from "./width.js";

export const Chars = {
    fillAround,
    fillLeft,
    fillRight,
    nextWordOffset,
    prevWordOffset,
    truncateLeft,
    truncateRight,
    width,
}
