// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { create } from "./create.js";
import { Element } from "../Element/index.js";
import { ElementOptions } from "../Element/index.js";
import { focus } from "./focus.js";
import { isAtBottom } from "./isAtBottom.js";
import { isAtTop } from "./isAtTop.js";
import { isSelectable } from "./isSelectable.js";
import { KeyEvent } from "../types.js";
import { MaybeReactive } from "@monstermann/signals";
import { Memo } from "@monstermann/signals";
import { MouseEvent } from "../types.js";
import { nextSelectable } from "./nextSelectable.js";
import { prevSelectable } from "./prevSelectable.js";
import { scrollDownBy } from "./scrollDownBy.js";
import { scrollDownHalfPage } from "./scrollDownHalfPage.js";
import { scrollDownPage } from "./scrollDownPage.js";
import { scrollToBottom } from "./scrollToBottom.js";
import { scrollToTop } from "./scrollToTop.js";
import { scrollUpBy } from "./scrollUpBy.js";
import { scrollUpHalfPage } from "./scrollUpHalfPage.js";
import { scrollUpPage } from "./scrollUpPage.js";
import { select } from "./select.js";
import { selectFirst } from "./selectFirst.js";
import { selectLast } from "./selectLast.js";
import { selectNext } from "./selectNext.js";
import { selectPrev } from "./selectPrev.js";
import { setScrollTop } from "./setScrollTop.js";
import { Signal } from "@monstermann/signals";
import { Text } from "../Text/index.js";

type ListItem = { isSelectable?: boolean } & Record<PropertyKey, any>

interface List<T extends ListItem = any> extends Element {
    lines: Memo<readonly T[]>
    maxScrollTop: Memo<number>
    scrollTop: Signal<number>
    selectedIdx: Signal<number>
    selectedLine: Memo<T | undefined>
    render: () => void
}

interface ListOptions<T extends ListItem> extends ElementOptions {
    lines: MaybeReactive<readonly T[]>
    onKeypress?: (event: KeyEvent) => void
    onMouse?: (event: MouseEvent) => void
    renderLine: (line: {
        data: T
        index: number
        isSelected: boolean
        list: List<T>
    }) => Text[]
}

declare namespace List {
    export {
        create,
        focus,
        isAtBottom,
        isAtTop,
        isSelectable,
        nextSelectable,
        prevSelectable,
        scrollDownBy,
        scrollDownHalfPage,
        scrollDownPage,
        scrollToBottom,
        scrollToTop,
        scrollUpBy,
        scrollUpHalfPage,
        scrollUpPage,
        select,
        selectFirst,
        selectLast,
        selectNext,
        selectPrev,
        setScrollTop,
    }
}

export {
    List,
    ListItem,
    ListOptions,
}
