// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { collapse } from "./collapse.js";
import { create } from "./create.js";
import { expand } from "./expand.js";
import { MaybeReactive } from "@monstermann/signals";
import { Memo } from "@monstermann/signals";
import { Signal } from "@monstermann/signals";
import { toggle } from "./toggle.js";
import { TokenLine } from "./internals/Tokenizer.js";

interface Data {
    expanded: Signal<ReadonlySet<string>>
    lines: Memo<readonly TokenLine[]>
}

interface DataOptions {
    data: MaybeReactive<unknown>
    indentation?: MaybeReactive<number>
    maxWidth?: MaybeReactive<number>
}

declare namespace Data {
    export {
        collapse,
        create,
        expand,
        toggle,
    }
}

export {
    Data,
    DataOptions,
}
